### ISSUE TITLE
remove is not defined?

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#16]
[This program](http://www.wescheme.org/view?publicId=Wpu9FckiVK) uses WeScheme's built-in `remove` function, which is undefined in Spyret

**Comment by ds26gte** [comment]
Fixed in a838f73 and ds26gte/pyret-lang@499ebc7.

- `remove` was not mentioned in the wescheme.org Documentation tab. I checked if WeScheme also offered `remq` and `remv`, but it doesn't.

- needed to define a `_spyret_remove` because Pyret's own `remove` is not quite the same. WeScheme's flips the argument order, and only removes the first occurrence.

**Comment by schanzer** [comment]
Awesome - and sorry about the WeScheme documentation being incomplete. We have to make changes to those docs *by hand*, since there's no automated way to pulling the info from the DrRacket Docs based on a list of symbols. 

There are a small number (< 5) primitives that I've added to WeScheme over the last few years, so these are few and far between.
