### ISSUE TITLE
Roughnum equality should be allowed

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#26]
Bootstrap:1 should not expose students to the complexities of roughnums just yet - can we have spyret equality use a tolerance of 0.001 instead? Note: this should only be the case for roughnums.

**Comment by schanzer** [comment]
In other words, '(EXAMPLE (exact->inexact 2) (exact->inexact 2))' should work

**Comment by ds26gte** [comment]
Fixed in ds26gte/pyret-lang@11396e8.

Made it Scheme-like rather than positing an arbitrary tolerance. I.e., `=` will give true and `EXAMPLE` will succeed only if the exact versions of the corresponding roughnums are equal. I think this is a better solution because using a hidden tolerance fails trichotomy, which can be just as baffling as roughnum equality failing.

**Comment by schanzer** [comment]
Beautiful! Confirmed.
