### ISSUE TITLE
Loading user-defined libraries from WeScheme

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#43]
http://www.wescheme.org/view?publicId=7oyY3AR4B7 
I know this has worked in the past. Regression?

Reported by Tiina Partnanen

**Comment by ds26gte** [comment]
Fixed, partly.  Not a regression error. This one had multiple issues: There was a forward reference which I've now accommodated. Also: the translation of `local` (and `letrec`) needed to be updated.

The remaining caveat is that this works if you invoke Patch as `http://patch-editor.herokuapp.com` (unsecure) rather than `https://patch-editor.herokuapp.com`.  This is because the the WeScheme legacy module is readable only as an `http://` URI.  Changing it to `https://` causes a "mismatch" error: Apparently we can't call a `http://` URI via jQuery from an `https://` site.

**Comment by ds26gte** [comment]
Fixed in toto. Thanks to @awstlaur, legacy modules are now available via both https and http URIs (`https://wescheme-hrd-2.appspot.com` and `http://www.wescheme.org`). Patch will choose one of them based on how it itself was invoked.

**Comment by schanzer** [comment]
Fantastic!
