### ISSUE TITLE
Problems with top-level definitions 

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#44]
Reduced test case here: https://drive.google.com/file/d/0BzzMl1BJlJDkNDJtbk1FU2NWeGs/view?usp=sharing

Reported by Tiina Partnanen

**Comment by ds26gte** [comment]
Thanks, fixed. (Note for the curious: The example has no forward reference. Nevertheless it failed because Patch does some bubbling-up of non-function definitions to ensure that at least some cases of forward reference _are_ tolerated. This fix adds a bit more case analysis to this decision-making.)

**Comment by schanzer** [comment]
Terrific - nice work, and thanks for the explanation!
