### ISSUE TITLE
"Open" button appears even if the user is not connected to GDrive

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#72]
Clicking it before connecting to GDrive results in a cryptic error.

In CPO, this button is hidden until the user connects to GDrive. At the very least, we should mimic this behavior. But I wonder -- if user is logged in, shouldn't _always_ connect to their Drive? That's the entire point of logging in, isn't it?

**Comment by ds26gte** [comment]
Fixed.

I think being logged in does always imply GDrive connectedness. There was a glitch because the user was _not_ actually logged in _sometimes_ because of a failure to get a refresh token the first time around. I've changed it so that the initial login does try to authorize using a forced prompt in such cases.
