### ISSUE TITLE
Tiina's Homemade WeScheme Libraries

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#76]
Likely due to a multiple bugs, but for now I'm just creating a meta-issue to track them all.

1) http://www.wescheme.org/view?publicId=bcriaG8BkK
This is not working at all. Getting multiple errors, not opening the animation (e.g. World) at all.

2) http://www.wescheme.org/view?publicId=3to4cxt2X2
This works partly (shows the animation windows, gets the first input correctly, then crashes). This bug might have something to do with map or apply e.g. not directly a legacy lib issue?

3) http://www.wescheme.org/view?publicId=GPgDQaJMHJ 
This is not working at all. Errors for argmax and sort...

**Comment by ds26gte** [comment]
#3 fixed. Added definition for `argmax` and `sort` (the latter just an alias for `quicksort`).

**Comment by ds26gte** [comment]
No. 2 also fixed. Previous definition of Patch `map` was not stack-safe when the mapped function contained a call to `big-bang`. Re-implemented `map` to be more robust.

**Comment by ds26gte** [comment]
No. 1 also fixed. Fixed issues relating to this are:
1. Pyret's `reverse` (now?) needed to have its signature explicitly declared in `pyret-lang`.
2. Pyret primitive `repeat` (not used in WeScheme) was defined in this file. Hence, the id `repeat` needed to be made safe for redefinition via transliteration.
3. The ids introduced by `define-struct` should go through transliteration (since WeScheme ids tend to go beyond the typical alphanumerics), but they should not go through `symbolMap`, which converts meaningful WeScheme primitive ids into meaningful Pyret primitive ids (e.g., `angle?` to `is-angle`). Rewrote `pyretizeSymbol` to divide these two tasks, so one of them can be reverted when `define-struct` is parsed.
4. `stop-when` was called with a second argument (which is not documented in WeScheme, and seems to be a Racketism). This optional second arg is ignored for now.

**Comment by ds26gte** [comment]
P.S. No. 1 had another issue:
5. `record?` is a legacy handler-creator (another Racketism) used in this case. Created a dummy value for it now. A disadvantage is that the user can't define `record?` in their modules. (In general, Pyret won't allow redefinition. See sub-issue 2 above, where `repeat` had to be transliterated in order to allow the user to define it.)

**Comment by schanzer** [comment]
Phenomenal! 

Re: stop-when with 'last picture'. This is still a feature I desperately want added to reactors in some way. Worth pinging Joe to see if this is slated for the near future.

**Comment by ds26gte** [comment]
Added a functioning last-picture argument for `stop-when`. It shows a final picture now, but unlike in WeScheme, there's a triangle marking the final cursor position.
